export const evfolyamOptions = [
    { value: "", label: "Válaszd ki az évfolyamod:" },
    { value: "Kent-Kupé", label: "Kent-Kupé" },
    { value: "Tarka-Barka", label: "Tarka-Barka" },
    { value: "Buda-Pest", label: "Buda-Pest" },
    { value: "Coca-Cola", label: "Coca-Cola" },
    { value: "Hepe-Hupa", label: "Hepe-Hupa" },
    { value: "Szinusz-Koszinus", label: "Szinusz-Koszinus" },
    { value: "Veni-Vidi-Vicci", label: "Veni-Vidi-Vicci" },
    { value: "Cassiopeia", label: "Cassiopeia" },
    { value: "Carpe-Diem", label: "Carpe-Diem" },
    { value: "Subi-Dubi", label: "Subi-Dubi" },
    { value: "Black-Jack", label: "Black-Jack" },
    { value: "Umpa-Lumpa", label: "Umpa-Lumpa" },
  ];


  export const patronusOptions = [
    { value: "angyal_krisztina_andrea", label: "Angyal Krisztina Andrea" },
    { value: "bajko_balint", label: "Bajkó Bálint" },
    { value: "bajkone_turoczi_judit", label: "Bajkóné Turóczi Judit" },
    { value: "bako_katalin", label: "Bakó Katalin" },
    { value: "baranyai_istvan", label: "Baranyai István" },
    { value: "barlay_zsuzsanna", label: "Barlay Zsuzsanna" },
    { value: "bede_kiss_noemi", label: "Bede-Kiss Noémi" },
    { value: "beko_edit", label: "Bekő Edit" },
    { value: "berta_anna_maria", label: "Berta Anna Mária" },
    { value: "birloni_szilvia", label: "Birloni Szilvia" },
    { value: "bodonczy_andrea", label: "Bodonczy Andrea" },
    { value: "borsik_lili_katinka", label: "Borsik Lili Katinka" },
    { value: "bucsi_szilvia", label: "Bucsi Szilvia" },
    { value: "chamfrault_catherine", label: "Chamfrault Chatherine" },
    { value: "chrenko_timea", label: "Chrenkó Tímea" },
    { value: "cedulas_karolina", label: "Czédulás Karolina" },
    { value: "cselenyi_katalin", label: "Cselényi Katalin" },
    { value: "cserne_tatai_reka", label: "Cserné Tatai Réka" },
    { value: "csicskar_miatovics_krisztina", label: "Csicskár-Miátovics Krisztina" },
    { value: "csizi_kelemen_zsuzsanna_veronika", label: "Csizi-Kelemen Zsuzsanna Veronika" },
    { value: "david_judit", label: "Dávid Judit" },
    { value: "deszeri_csaba", label: "Dezséri Csaba" },
    { value: "devai_zsofia", label: "Dévai Zsófia" },
    { value: "driszkune_szilagyi_eva", label: "Driszkuné Szilágyi Éva" },
    { value: "emmertne_veres_reka", label: "Emmertné Veres Réka" },
    { value: "erdei_edina", label: "Erdei Edina" },
    { value: "gaal_orsolya", label: "Gaál Orsolya" },
    { value: "gomboczne_erdei_monika", label: "Gomboczné Erdei Mónika" },
    { value: "gortva_attila", label: "Gortva Attila" },
    { value: "gottweisz_timea", label: "Gottweisz Tímea" },
    { value: "halasz_marton", label: "Halász Márton" },
    { value: "halasz_sandor", label: "Halász Sándor" },
    { value: "dr_hantos_istvan", label: "dr. Hantos István" },
    { value: "hanula_erika", label: "Hanula Erika" },
    { value: "hegymegi_istvanne", label: "Hegymegi Istvánné" },
    { value: "hermanovszki_szilvia", label: "Hermanovszki Szilvia" },
    { value: "hites_borbala", label: "Hites Borbála" },
    { value: "hollik_edina", label: "Hollik Edina" },
    { value: "horn_agnes", label: "Horn Ágnes" },
    { value: "horn_gyorgy", label: "Horn György" },
    { value: "horvath_zoltan", label: "Horváth Zoltán" },
    { value: "hugli_balint", label: "Hugli Bálint" },
    { value: "huszar_walla_julia", label: "Huszár-Walla Júlia" },
    { value: "ivanyi_dora_eszter", label: "Iványi Dóra Eszter" },
    { value: "izsone_hubay_katalin", label: "Izsóné Hubay Katalin" },
    { value: "jakab_peter", label: "Jakab Péter" },
    { value: "janzso_krisztina", label: "Janzsó Krisztina" },
    { value: "juhasz_ivan", label: "Juhász Iván" },
    { value: "juhasz_rita", label: "Juhász Rita" },
    { value: "kallo_adrienn", label: "Kalló Adrienn" },
    { value: "kalman_eva", label: "Kálmán Éva" },
    { value: "kando_michael_francis", label: "Kandó, Michael Francis" },
    { value: "kardos_eva", label: "Kardos Éva" },
    { value: "kasza_nikoletta", label: "Kasza Nikoletta" },
    { value: "kiss_virag", label: "Kiss Virág" },
    { value: "kolozsi_beata", label: "Kolozsi Beáta" },
    { value: "kozma_andrea", label: "Kozma Andrea" },
    { value: "kozma_fruzsina", label: "Kozma Fruzsina" },
    { value: "kuczo_csilla", label: "Kuczó Csilla" },
    { value: "laffer_zsuzsanna", label: "Laffer Zsuzsanna" },
    { value: "letay_marton_karoly", label: "Létay Márton Károly" },
    { value: "lorinc_laszlo", label: "Lőrinc László" },
    { value: "makany_beata", label: "Makány Beáta" },
    { value: "mendelovics_zsuzsanna", label: "Mendelovics Zsuzsanna" },
    { value: "miakich_gabor", label: "Miakich Gábor" },
    { value: "micsko_robert", label: "Micskó Róbert" },
    { value: "mlynarik_agnes", label: "Mlynarik Ágnes" },
    { value: "nadori_gergely", label: "Nádori Gergely" },
    { value: "nagy_melykuti_luca", label: "Nagy Mélykuti Luca" },
    { value: "niedermuller_anna", label: "Niedermüller Anna" },
    { value: "nogradi_zoltan", label: "Nógrádi Zoltán" },
    { value: "nyitrai_sara", label: "Nyitrai Sára" },
    { value: "ozorai_judit", label: "Ozorai Judit" },
    { value: "papp_gergely", label: "Papp Gergely" },
    { value: "papucsekne_mecseki_petra", label: "Papucsekné Mecseki Petra" },
    { value: "pasztor_judit", label: "Pásztor Judit" },
    { value: "pataky_vanko_szilvia", label: "Pataky-Vankó Szilvia" },
    { value: "patrik_pirk_anett", label: "Patrik-Pirk Anett" },
    { value: "pava_hajnalka_gyongyi", label: "Páva Hajnalka Gyöngyi" },
    { value: "dr_petho_szilvia", label: "dr. Pethő Szilvia" },
    { value: "philipp_gyorgy", label: "Philipp György" },
    { value: "polya_bella_reka", label: "Pólya Bella Réka" },
    { value: "posfai_aron", label: "Pósfai Áron" },
    { value: "puig_jose_mariano", label: "Puig, José Mariano" },
    { value: "puskas_annamaria", label: "Puskás Annamária" },
    { value: "reiter_daniel", label: "Reiter Dániel" },
    { value: "ronai_robert", label: "Rónai Róbert" },
    { value: "sajo_eszter", label: "Sajó Eszter" },
    { value: "sik_eszter", label: "Sik Eszter" },
    { value: "sinka_andrea", label: "Sinka Andrea" },
    { value: "sinka_noemi", label: "Sinka Noémi" },
    { value: "sofalvi_civin_zsuzsa", label: "Sófalvi-Civin Zsuzsa" },
    { value: "solyom_viktoria_agnes", label: "Sólyom Viktória Ágnes" },
    { value: "dr_stefany_judit", label: "dr. Stefány Judit" },
    { value: "stock_martin", label: "Stock Martin" },
    { value: "sulyok_pap_zsuzsa", label: "Sulyok Pap Zsuzsa" },
    { value: "suranyi_szabolcs", label: "Surányi Szabolcs" },
    { value: "szabo_imre", label: "Szabó Imre" },
    { value: "szalay_fegyver_erika", label: "Szalay-Fegyver Erika" },
    { value: "szalontai_agnes", label: "Szalontai Ágnes" },
    { value: "szedresi_julia", label: "Szedresi Júlia" },
    { value: "szeles_gabor", label: "Széles Gábor" },
    { value: "szentirmaine_pecsi_anna", label: "Szentirmainé Pécsi Anna" },
    { value: "szigeti_rita", label: "Szigeti Rita" },
    { value: "szigeti_szilvia", label: "Szigeti Szilvia" },
    { value: "szondi_gyorgy", label: "Szondi György" },
    { value: "szots_erika", label: "Szőts Erika" },
    { value: "szucs_tamas", label: "Szűcs Tamás" },
    { value: "szucs_sipos_anita", label: "Szűcs-Sipos Anita" },
    { value: "takacs_agnes", label: "Takács Ágnes" },
    { value: "takacs_peter", label: "Takács Péter" },
    { value: "terek_bernadett", label: "Terék Bernadett" },
    { value: "teremy_laszlo", label: "Teremy László" },
    { value: "timar_adam", label: "Timár Ádám" },
    { value: "timar_attila", label: "Timár Attila" },
    { value: "timar_fanni", label: "Timár Fanni" },
    { value: "tornay_zsuzsanna", label: "Tornay Zsuzsanna" },
    { value: "totl_marton", label: "Töltl Márton" },
    { value: "tuskene_molnar_anita", label: "Tüskéné Molnár Anita" },
    { value: "ungvary_fanni_dora", label: "Ungváry Fanni Dóra" },
    { value: "valasek_zsuzsanna", label: "Valasek Zsuzsanna" },
    { value: "varhegyi_barbara", label: "Várhegyi Barbara" },
    { value: "varro_maria", label: "Varró Mária" },
    { value: "vesztergombi_krisztina", label: "Vesztergombi Krisztina" },
    { value: "viczian_csenge_sara", label: "Viczián Csenge Sára" },
    { value: "vidra_vivien", label: "Vidra Vivien" },
    { value: "voko_krisztina_monika", label: "Vokó Krisztina Mónika" },
    { value: "voros_bujk_zsuzsa", label: "Vörös-Bujk Zsuzsa" },
    { value: "zaccomer_maria", label: "Zaccomer Mária" },
    { value: "zelko_katalin", label: "Zelkó Katalin" },
    { value: "zsigrai_eszter_anna", label: "Zsigrai Eszter Anna" },
    { value: "zsisku_iren", label: "Zsisku Irén" }
  ];
  


  export const alkotoOptions = [
    { label: "Újonnan meghirdetett foglalkozások", options: [
      { value: "adattudos", label: "Adattudós (Szalai Sándor) – szakkör" },
      { value: "angol_ujsagiras", label: "Angol nyelvű iskolai újságírás – alkotókör" },
      { value: "art_history_english", label: "Art History in English (Michael Webb) – szakkör" },
      { value: "diszitoszobraszat", label: "Díszítőszobrászat (Fenyvesi Edit) Kiscelli – alkotókör" },
      { value: "filmes_alkotokor", label: "Filmes, mozgóképes alkotókör (Csicskár Dávid) Kiscelli – alkotókör" },
      { value: "grafika", label: "Grafika (Fenyvesi Edit) Kiscelli – alkotókör" },
      { value: "hetedikes_szinjatszokor", label: "Hetedikes színjátszókör (Nádori Gergely) – alkotókör" },
      { value: "kepzomuveszeti_abc", label: "Képzőművészeti „ABC” (Fenyvesi Edit) Kiscelli – alkotókör" },
      { value: "kortars_segito", label: "Kortárs segítő (Pólya Bella) – szakkör" },
      { value: "korus", label: "Kórus (Philipp György) Kiscelli – alkotókör" },
      { value: "kreativ_zene", label: "Kreatív zene (Barlay Zsuzsanna, Philipp György) – alkotókör" },
      { value: "machinarium", label: "Machinarium (Dezséri Csaba) Kiscelli – szakkör" },
      { value: "okoklub", label: "Ökoklub (Chrenkó Tímea, Kuczó Csilla, Miátovics Krisztina, Nagy-Mélykuti Luca, Stefány Judit) – szakkör" },
      { value: "res_publica", label: "Res Publica (Bodonczy Andrea) – szakkör" },
      { value: "szinjatszo", label: "Színjátszó (Zsurzs Katalin, Csicskár Dávid) Kiscelli – alkotókör" },
    ]},
    { label: "Művészeti alkotókörök (folyamatosan működő)", options: [
      { value: "analog_foto", label: "Analóg fotó (Kolozsi Beáta)" },
      { value: "digitalis_targykeszites", label: "Digitális tárgykészítés (Nádori Gergely)" },
      { value: "fenytechnika_show_vilagitas", label: "Fénytechnika és show világítás (Gortva Attila)" },
      { value: "foto", label: "Fotó (Kolozsi Beáta)" },
      { value: "francia_szinhaz", label: "Francia Színház (Puskás Annamária, Károlyi Ábel)" },
      { value: "hangtechnika", label: "Hangtechnika (Gortva Attila)" },
      { value: "kepzomuveszet", label: "Képzőművészet (Szabó Imre)" },
      { value: "keramia", label: "Kerámia (Tatai Réka)" },
      { value: "kortars_kepzomuveszet", label: "Kortárs képzőművészet (Ulbert Ádám)" },
      { value: "kreativ_rajz", label: "Kreatív rajz (Borsik Lili)" },
      { value: "radio", label: "Rádió (Gortva Attila)" },
      { value: "stilus", label: "Stílus (Bodonczy Andrea)" },
      { value: "szubjektiv_ujsagiras", label: "Szubjektív újságírás (Baranyai István) * weblap * blog * FB" },
      { value: "trupp_szinjatszo", label: "Trupp színjátszó (Lőrinc László)" },
      { value: "ujsagiras_kiscelli", label: "Újságírás (Gottweisz Tímea) – Kiscelli" },
      { value: "video", label: "Videó (Gortva Attila, Halász Sándor) * éves munkaterv" },
    ]},
    { label: "Specializációk (munkaközösségek által meghirdetett programok)", options: [
      { value: "disputa", label: "Disputa (Juhász Iván)" },
      { value: "irodalom_felsofokon", label: "Irodalom felsőfokon (Bodonczy Andrea)" },
      { value: "euro_parl_nagykovetiskola", label: "Európai Parlament Nagykövetiskola (Nagy-Mélykuti Luca, Zábráczki Anett)" },
      { value: "matek_tehetseg_7", label: "Matematika tehetséggondozó és versenyfelkészítő (7. évf.) (Pásztor Judit)" },
      { value: "matek_tehetseg_8", label: "Matematika tehetséggondozó és versenyfelkészítő (8. évf.) (Baranyai István)" },
      { value: "matek_tehetseg_9", label: "Matematika tehetséggondozó és versenyfelkészítő (9. évf.) (Szondi György)" },
      { value: "matek_tehetseg_11ny", label: "Matematika tehetséggondozó és versenyfelkészítő (11ny. évf.) (Birloni Szilvia)" },
      { value: "matek_emelt_12n", label: "Matematika emelt plusz (12n. évf.) (Pásztor Judit)" },
      { value: "lego_robotepito", label: "LEGO Robotépítő (Mindstorms) szakkör (Nádori Gergely, Pásztor Judit)" },
      { value: "csillagaszat", label: "Csillagászat (Nagy Viktor, Reiter Dániel)" },
      { value: "elsosegely", label: "Elsősegély * weblap * képek" },
      { value: "kemia_erettsegizok", label: "Kémiai kísérletek érettségizőknek (11-12. évf.) (Kelemen Veronika)" },
      { value: "raketaepites", label: "Rakétaépítés műhely (Nagy Viktor, Reiter Dániel, Rokolya Kornél)" },
      { value: "term_tud_lab", label: "Természettudományos labor (Várhegyi Barbara)" },
      { value: "angol_felkeszito_11ny", label: "Angol – Angol felkészítő (11ny) (Sófalvi-Civin Zsuzsa, Tornay Zsuzsanna)" },
      { value: "angol_circle_speak_12n", label: "Angol – Társadalomismeret / Circle Speak (12n. évf.) (Kandó Mihály)" },
      { value: "angol_social_studies_12", label: "Angol – Társadalomismeret / Social Studies (12. évf.) (Kandó Mihály)" },
      { value: "japan_kezdo_halado", label: "Japán – Kezdő / Haladó (Baross Dorottya)" },
      { value: "spanyol_tarsalgas_12n", label: "Spanyol társalgás (12n. évf.) (Zábráczki Anett)" },
    ]},
    { label: "Testnevelés specializációk (sportkörök)", options: [
      { value: "aerobik", label: "Aerobik (Driszkuné Szilágyi Éva, Sulyok-Pap Zsuzsanna)" },
      { value: "aerobik_kiscelli", label: "Aerobik – Kiscelli (Csicskár-Miátovics Krisztina)" },
      { value: "asztalitenisz", label: "Asztalitenisz (Vankó Szilvia)" },
      { value: "asztalitenisz_kiscelli", label: "Asztalitenisz – Kiscelli (Mártonffy Eszter)" },
      { value: "badminton", label: "Badminton (Sulyok-Pap Zsuzsanna)" },
      { value: "badminton_kiscelli", label: "Badminton – Kiscelli (Mártonffy Eszter)" },
      { value: "evezes", label: "Evezés – Kiscelli (Papp Zsolt)" },
      { value: "kosarlabda_fiu", label: "Kosárlabda – fiú (Földes Ágnes)" },
      { value: "kosarlabda_lany", label: "Kosárlabda – lány (Földes Ágnes)" },
      { value: "kosarlabda_kiscelli", label: "Kosárlabda – Kiscelli (Földes Ágnes)" },
      { value: "kuzdosportok", label: "Küzdősportok (Tóth Béla)" },
      { value: "labdarugas_kiscelli", label: "Labdarúgás – Kiscelli (Lőrinc László)" },
      { value: "rsg", label: "Ritmikus gimnasztika (Vankó Szilvia)" },
      { value: "taekwon_do", label: "Taekwon-do (Nagy László)" },
      { value: "triatlon", label: "Triatlon (Driszkuné Szilágyi Éva)" },
      { value: "ultrafutas", label: "Ultrafutás (Csécsei Zoltán)" },
      { value: "ultimulogyakorlas", label: "Ultimúló gyakorlás (Lőrinc László)" },
      { value: "valogatott_felkeszites", label: "Válogatott felkészítés (Gyulai Annamária)" },
      { value: "zsonglor", label: "Zsonglőr (Miátovics Krisztina)" },
    ]},
    { label: "Tanulást segítő programok (9-12. évf.)", options: [
      { value: "biologia_tehetseg", label: "Biológia tehetséggondozás (10-12. évf.) (Várhegyi Barbara)" },
      { value: "biologia_tehetseg_9", label: "Biológia tehetséggondozás (9. évf.) (Reiter Dániel)" },
      { value: "emelt_szintu_irasbeli_felkeszito", label: "Emelt szintű írásbeli érettségi felkészítő – magyar nyelv és irodalom (12. évf.) (Mayerné Marton Éva)" },
      { value: "tortenelem_irasbeli_emelt_12n", label: "Emelt szintű írásbeli érettségi felkészítő – történelem (12n. évf.) (Török Lajos)" },
      { value: "tortenelem_irasbeli_emelt_11ny", label: "Emelt szintű írásbeli érettségi felkészítő – történelem (11ny. évf.) (Pölös Zoltán)" },
      { value: "tortenelem_szobeli_felkeszito", label: "Emelt szintű szóbeli érettségi felkészítő – történelem (11-12. évf.) (Török Lajos, Pölös Zoltán)" },
      { value: "magyar_emelt_szintu_felkeszito", label: "Magyar nyelv és irodalom emelt szintű szóbeli felkészítő (11-12. évf.) (Nagy Emese)" },
      { value: "matematika_irasbeli_emelt", label: "Matematika írásbeli emelt szintű érettségi felkészítő (11-12. évf.) (Szondi György)" },
      { value: "nemeth_felkeszito", label: "Német írásbeli emelt szintű érettségi felkészítő (12. évf.) (Birloni Szilvia)" },
      { value: "olasz_irasbeli_emelt_felkeszito", label: "Olasz írásbeli emelt szintű érettségi felkészítő (12. évf.) (Csécsei Zoltán)" },
      { value: "olasz_szobeli_emelt_felkeszito", label: "Olasz szóbeli emelt szintű érettségi felkészítő (12. évf.) (Pongrácz Ferencné)" },
      { value: "spanyol_felkeszito", label: "Spanyol írásbeli és szóbeli emelt szintű érettségi felkészítő (11-12. évf.) (Kandó Mihály)" },
    ]},
  ];
  
